### PR TITLE
cast parameter to `make_pair` for macOS

### LINKED ISSUE #29: Unable to build on macOS 14.0 arm64
Build fails with the following error:
```makefile
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:544:12: error: no matching constructor for initialization of 'pair<typename __unwrap_ref_decay<volatile long &>::type, typename __unwrap_ref_decay<long &>::type>' (aka 'pair<long, long>')
    return pair<typename __unwrap_ref_decay<_T1>::type, typename __unwrap_ref_decay<_T2>::type>
           ^
``` 

Output of ./configure:
```
checking build system type... arm-apple-darwin23.0.0
checking host system type... arm-apple-darwin23.0.0
checking target system type... arm-apple-darwin23.0.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... acscripts/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking building for Win32... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... rm: conftest.dSYM: is a directory
yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for ranlib... ranlib
checking for pkg-config... /opt/homebrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SDL... yes
checking for wx-config... /opt/homebrew/bin/wx-config
checking for wxWidgets version >= 2.8.9... yes (version 3.2.2)
checking for wxWidgets static library... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands
``` 

Full output of make:
```makefile
Making all in src
depbase=`echo WMain.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"sound-of-sorting\" -DPACKAGE_TARNAME=\"sound-of-sorting\" -DPACKAGE_VERSION=\"0.6.5\" -DPACKAGE_STRING=\"sound-of-sorting\ 0.6.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sound-of-sorting\" -DVERSION=\"0.6.5\" -I.    -W -Wall -I/opt/homebrew/lib/wx/include/osx_cocoa-unicode-3.2 -I/opt/homebrew/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -D_THREAD_SAFE -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -g -Wno-unused-local-typedefs -MT WMain.o -MD -MP -MF $depbase.Tpo -c -o WMain.o WMain.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from WMain.cpp:23:
In file included from ./WMain.h:26:
In file included from /opt/homebrew/include/wx-3.2/wx/wx.h:24:
In file included from /opt/homebrew/include/wx-3.2/wx/event.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/cursor.h:75:
/opt/homebrew/include/wx-3.2/wx/utils.h:749:35: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
1 warning generated.
depbase=`echo wxg/WMain_wxg.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"sound-of-sorting\" -DPACKAGE_TARNAME=\"sound-of-sorting\" -DPACKAGE_VERSION=\"0.6.5\" -DPACKAGE_STRING=\"sound-of-sorting\ 0.6.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sound-of-sorting\" -DVERSION=\"0.6.5\" -I.    -W -Wall -I/opt/homebrew/lib/wx/include/osx_cocoa-unicode-3.2 -I/opt/homebrew/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -D_THREAD_SAFE -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -g -Wno-unused-local-typedefs -MT wxg/WMain_wxg.o -MD -MP -MF $depbase.Tpo -c -o wxg/WMain_wxg.o wxg/WMain_wxg.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from wxg/WMain_wxg.cpp:12:
In file included from /opt/homebrew/include/wx-3.2/wx/wx.h:24:
In file included from /opt/homebrew/include/wx-3.2/wx/event.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/cursor.h:75:
/opt/homebrew/include/wx-3.2/wx/utils.h:749:35: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
1 warning generated.
depbase=`echo wxg/WAbout_wxg.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"sound-of-sorting\" -DPACKAGE_TARNAME=\"sound-of-sorting\" -DPACKAGE_VERSION=\"0.6.5\" -DPACKAGE_STRING=\"sound-of-sorting\ 0.6.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sound-of-sorting\" -DVERSION=\"0.6.5\" -I.    -W -Wall -I/opt/homebrew/lib/wx/include/osx_cocoa-unicode-3.2 -I/opt/homebrew/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -D_THREAD_SAFE -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -g -Wno-unused-local-typedefs -MT wxg/WAbout_wxg.o -MD -MP -MF $depbase.Tpo -c -o wxg/WAbout_wxg.o wxg/WAbout_wxg.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from wxg/WAbout_wxg.cpp:12:
In file included from /opt/homebrew/include/wx-3.2/wx/wx.h:24:
In file included from /opt/homebrew/include/wx-3.2/wx/event.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/cursor.h:75:
/opt/homebrew/include/wx-3.2/wx/utils.h:749:35: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
wxg/WAbout_wxg.cpp:37:25: warning: 'wxFont' is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants [-Wdeprecated-declarations]
    labelTitle->SetFont(wxFont(14, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("")));
                        ^
/opt/homebrew/include/wx-3.2/wx/osx/font.h:115:5: note: 'wxFont' has been explicitly marked deprecated here
    wxDEPRECATED_MSG("use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants")
    ^
/opt/homebrew/include/wx-3.2/wx/defs.h:654:54: note: expanded from macro 'wxDEPRECATED_MSG'
        #define wxDEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                     ^
wxg/WAbout_wxg.cpp:37:25: warning: 'wxFont' is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants [-Wdeprecated-declarations]
    labelTitle->SetFont(wxFont(14, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("")));
                        ^
/opt/homebrew/include/wx-3.2/wx/osx/font.h:115:5: note: 'wxFont' has been explicitly marked deprecated here
    wxDEPRECATED_MSG("use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants")
    ^
/opt/homebrew/include/wx-3.2/wx/defs.h:654:54: note: expanded from macro 'wxDEPRECATED_MSG'
        #define wxDEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
                                                     ^
3 warnings generated.
depbase=`echo WSortView.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"sound-of-sorting\" -DPACKAGE_TARNAME=\"sound-of-sorting\" -DPACKAGE_VERSION=\"0.6.5\" -DPACKAGE_STRING=\"sound-of-sorting\ 0.6.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sound-of-sorting\" -DVERSION=\"0.6.5\" -I.    -W -Wall -I/opt/homebrew/lib/wx/include/osx_cocoa-unicode-3.2 -I/opt/homebrew/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -D_THREAD_SAFE -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -g -Wno-unused-local-typedefs -MT WSortView.o -MD -MP -MF $depbase.Tpo -c -o WSortView.o WSortView.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from WSortView.cpp:24:
In file included from ./WSortView.h:27:
In file included from /opt/homebrew/include/wx-3.2/wx/wx.h:24:
In file included from /opt/homebrew/include/wx-3.2/wx/event.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/cursor.h:75:
/opt/homebrew/include/wx-3.2/wx/utils.h:749:35: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
1 warning generated.
depbase=`echo wxClickText.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"sound-of-sorting\" -DPACKAGE_TARNAME=\"sound-of-sorting\" -DPACKAGE_VERSION=\"0.6.5\" -DPACKAGE_STRING=\"sound-of-sorting\ 0.6.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sound-of-sorting\" -DVERSION=\"0.6.5\" -I.    -W -Wall -I/opt/homebrew/lib/wx/include/osx_cocoa-unicode-3.2 -I/opt/homebrew/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -D_THREAD_SAFE -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -g -Wno-unused-local-typedefs -MT wxClickText.o -MD -MP -MF $depbase.Tpo -c -o wxClickText.o wxClickText.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from wxClickText.cpp:25:
In file included from ./wxClickText.h:26:
In file included from /opt/homebrew/include/wx-3.2/wx/stattext.h:18:
In file included from /opt/homebrew/include/wx-3.2/wx/control.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/window.h:18:
In file included from /opt/homebrew/include/wx-3.2/wx/event.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/cursor.h:75:
/opt/homebrew/include/wx-3.2/wx/utils.h:749:35: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
1 warning generated.
depbase=`echo SortArray.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"sound-of-sorting\" -DPACKAGE_TARNAME=\"sound-of-sorting\" -DPACKAGE_VERSION=\"0.6.5\" -DPACKAGE_STRING=\"sound-of-sorting\ 0.6.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sound-of-sorting\" -DVERSION=\"0.6.5\" -I.    -W -Wall -I/opt/homebrew/lib/wx/include/osx_cocoa-unicode-3.2 -I/opt/homebrew/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -D_THREAD_SAFE -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -g -Wno-unused-local-typedefs -MT SortArray.o -MD -MP -MF $depbase.Tpo -c -o SortArray.o SortArray.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from SortArray.cpp:24:
In file included from ./SortArray.h:33:
In file included from /opt/homebrew/include/wx-3.2/wx/ctrlsub.h:19:
In file included from /opt/homebrew/include/wx-3.2/wx/control.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/window.h:18:
In file included from /opt/homebrew/include/wx-3.2/wx/event.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/cursor.h:75:
/opt/homebrew/include/wx-3.2/wx/utils.h:749:35: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
1 warning generated.
depbase=`echo SortSound.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"sound-of-sorting\" -DPACKAGE_TARNAME=\"sound-of-sorting\" -DPACKAGE_VERSION=\"0.6.5\" -DPACKAGE_STRING=\"sound-of-sorting\ 0.6.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sound-of-sorting\" -DVERSION=\"0.6.5\" -I.    -W -Wall -I/opt/homebrew/lib/wx/include/osx_cocoa-unicode-3.2 -I/opt/homebrew/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -D_THREAD_SAFE -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -g -Wno-unused-local-typedefs -MT SortSound.o -MD -MP -MF $depbase.Tpo -c -o SortSound.o SortSound.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from SortSound.cpp:33:
In file included from ./WSortView.h:27:
In file included from /opt/homebrew/include/wx-3.2/wx/wx.h:24:
In file included from /opt/homebrew/include/wx-3.2/wx/event.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/cursor.h:75:
/opt/homebrew/include/wx-3.2/wx/utils.h:749:35: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
1 warning generated.
depbase=`echo SortAlgo.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"sound-of-sorting\" -DPACKAGE_TARNAME=\"sound-of-sorting\" -DPACKAGE_VERSION=\"0.6.5\" -DPACKAGE_STRING=\"sound-of-sorting\ 0.6.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sound-of-sorting\" -DVERSION=\"0.6.5\" -I.    -W -Wall -I/opt/homebrew/lib/wx/include/osx_cocoa-unicode-3.2 -I/opt/homebrew/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -D_THREAD_SAFE -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -g -Wno-unused-local-typedefs -MT SortAlgo.o -MD -MP -MF $depbase.Tpo -c -o SortAlgo.o SortAlgo.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from SortAlgo.cpp:34:
In file included from ./SortAlgo.h:34:
In file included from ./SortArray.h:33:
In file included from /opt/homebrew/include/wx-3.2/wx/ctrlsub.h:19:
In file included from /opt/homebrew/include/wx-3.2/wx/control.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/window.h:18:
In file included from /opt/homebrew/include/wx-3.2/wx/event.h:22:
In file included from /opt/homebrew/include/wx-3.2/wx/cursor.h:75:
/opt/homebrew/include/wx-3.2/wx/utils.h:749:35: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    wxEventLoop* m_modalEventLoop = NULL;
                                  ^
In file included from SortAlgo.cpp:34:
In file included from ./SortAlgo.h:33:
In file included from /opt/homebrew/include/wx-3.2/wx/string.h:37:
In file included from /opt/homebrew/include/wx-3.2/wx/strvararg.h:19:
In file included from /opt/homebrew/include/wx-3.2/wx/unichar.h:15:
In file included from /opt/homebrew/include/wx-3.2/wx/stringimpl.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:545:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/hash.h:24:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:544:12: error: no matching constructor for initialization of 'pair<typename __unwrap_ref_decay<volatile long &>::type, typename __unwrap_ref_decay<long &>::type>' (aka 'pair<long, long>')
    return pair<typename __unwrap_ref_decay<_T1>::type, typename __unwrap_ref_decay<_T2>::type>
           ^
SortAlgo.cpp:578:17: note: in instantiation of function template specialization 'std::make_pair<volatile long &, long &>' requested here
    return std::make_pair(i,j);
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:82:5: note: candidate constructor not viable: 1st argument ('volatile long') would lose volatile qualifier
    pair(_T1 const& __t1, _T2 const& __t2) : first(__t1), second(__t2) {}
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:74:5: note: candidate constructor not viable: requires 1 argument, but 2 were provided
    pair(pair const&) = default;
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:75:5: note: candidate constructor not viable: requires 1 argument, but 2 were provided
    pair(pair&&) = default;
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:86:5: note: candidate constructor template not viable: requires single argument '__p', but 2 arguments were provided
    pair(const pair<_U1, _U2>& __p) : first(__p.first), second(__p.second) {}
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/pair.h:79:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    pair() : first(), second() {}
    ^
1 warning and 1 error generated.
make[1]: *** [SortAlgo.o] Error 1
make: *** [all-recursive] Error 1
```

### PR DESCRIPTION
**Pull request by peterguy**
`make_pair` on macOS can't handle volatile longs, so cast the first parameter to a long.

Change affects the `Quick Sort LL` sort.

Tested by manually exercising sorts in UI.

Compiled correctly on Linux; did not test by running the UI on Linux.

Did not compile or test on Windows.

Closes #29

### CODE REVIEW

**Comment by Unbreakable-Syntax** [comment]
Hello, I tested out your proposed fix in Windows, and Quick Sort LL still works as usual, I will add this to my fork
